version: "3.8"
services:
    postgres:
        container_name: botpostgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=botanicaldb
            - POSTGRES_USER=my_botanical_buddy
            - POSTGRES_PASSWORD=b0tBudz41851322
    plantservice:
        container_name: botplantservice
        build: ./PlantService
        expose:
            - "9100"
        ports:
            - "9100:9100"
        depends_on:
            - "postgres"
