version: "3.8"
services:
    postgres:
        container_name: botpostgres
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=botanicaldb
            - POSTGRES_USER=my_botanical_buddy
            - POSTGRES_PASSWORD=b0tBudz41851322
    #plantservice:
    #    container_name: botplantservice
    #    build: ./PlantService
    #    expose:
    #        - "9100"
    #    ports:
    #        - "9100:9100"
    #    depends_on:
    #        - "postgres"
    journalservice:
        container_name: botjournalservice
        build: ./JournalService
        expose:
            - "9200"
        ports:
            - "9200:9200"
        depends_on:
            - "postgres"
    minio:
        container_name: minio
        image: docker.io/bitnami/minio:2022
        ports:
            - "8000:9000"
            - "8001:9001"
        environment:
            - MINIO_DEFAULT_BUCKETS=botanicalbuddies:public
            - MINIO_ROOT_USER=minioUser
            - MINIO_ROOT_PASSWORD=minioPass
        volumes:
            - './minio:/data'
