// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JournalService.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20220521204824_InitialJournalEntries")]
    partial class InitialJournalEntries
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JournalEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("entryId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EntryId"));

                    b.Property<int>("JournalId")
                        .HasColumnType("integer")
                        .HasColumnName("journalId");

                    b.Property<string>("EntryTitle")
                        .HasColumnType("text")
                        .HasColumnName("entryTitle");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<string>("PlantName")
                        .HasColumnType("text")
                        .HasColumnName("plantName");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plantId");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateCreated")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("EntryId")
                        .HasName("PK_EntryId");

                    b.ToTable("journalentries");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            JournalId = 1,
                            EntryTitle = "Plant is looking very healthy today!",
                            UserId = 1,
                            PlantName = "Monstera", 
                            PlantId = 1, 
                            Content = "What's everyone's thoughts?", 
                            DateCreated = DateTimeOffset.Now
                        },
                        new
                        {
                            EntryId = 2,
                            JournalId = 2,
                            EntryTitle = "Might need to start watering more...",
                            UserId = 1,
                            PlantName = "Fern", 
                            PlantId = 2, 
                            Content = "What's everyone's thoughts?", 
                            DateCreated = DateTimeOffset.Now
                        },
                        new
                        {
                            EntryId = 3,
                            JournalId = 1,
                            EntryTitle = "Oh no... it's withering :(",
                            UserId = 2,
                            PlantName = "Fern", 
                            PlantId = 2, 
                            Content = "What's everyone's thoughts?", 
                            DateCreated = DateTimeOffset.Now
                        });
                });

            modelBuilder.Entity("Journal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("journalId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JournalId"));

                    b.Property<string>("journalTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("journalTitle");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plantId");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateCreated")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("JournalId")
                        .HasName("PK_JournalId");

                    b.ToTable("journals");

                    b.HasData(
                        new
                        {
                            JournalId = 1, 
                            JournalTitle = "I water it everyday and it still won't love me.", 
                            UserId = 1, 
                            PlantId = 1, 
                            DateCreated = DateTimeOffset.Now 
                        },
                        new
                        {
                            JournalId = 2, 
                            JournalTitle = "Has anybody ever grown a hibiscus plant indoors before?", 
                            UserId = 2, 
                            PlantId = 1, 
                            DateCreated = DateTimeOffset.Now 
                        },
                        new
                        {
                            JournalId = 3, 
                            JournalTitle = "How do I get my coffee plant to produce beans?", 
                            UserId = 1, 
                            PlantId = 3, 
                            DateCreated = DateTimeOffset.Now 
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
