// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JournalService.Migrations
{
    [DbContext(typeof(JournalsDbContext))]
    partial class BotBudsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Journal", b =>
                {
                    b.Property<string>("JournalTitle")
                        .HasColumnType("text")
                        .HasColumnName("journalTitle");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<string>("PlantName")
                        .HasColumnType("text")
                        .HasColumnName("plantName");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plantId");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateCreated");

                    b.HasKey("PlantId", "UserId")
                        .HasName("PKComposite_PlantId");

                    b.ToTable("journals");

                    b.HasData(
                        new
                        {
                            JournalTitle = "Plant is looking very healthy today!",
                            UserId = 1,
                            PlantName = "Monstera", 
                            PlantId = 1, 
                            Content = "What's everyone's thoughts?", 
                            DateCreated = DateTimeOffset.Now
                        },
                        new
                        {
                            JournalTitle = "Might need to start watering more...",
                            UserId = 1,
                            PlantName = "Fern", 
                            PlantId = 2, 
                            Content = "What's everyone's thoughts?", 
                            DateCreated = DateTimeOffset.Now
                        },
                        new
                        {
                            JournalTitle = "Oh no... it's withering :(",
                            UserId = 2,
                            PlantName = "Fern", 
                            PlantId = 2, 
                            Content = "What's everyone's thoughts?", 
                            DateCreated = DateTimeOffset.Now
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
