// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PlantService.Migrations
{
    [DbContext(typeof(PlantsDbContext))]
    partial class BotBudsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Plant", b =>
                {
                    b.Property<string>("PlantName")
                        .HasColumnType("text")
                        .HasColumnName("plantName");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("userId");

                    b.Property<DateTimeOffset>("DateAcquired")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dateAcquired");

                    b.Property<DateTimeOffset>("LastFertilizeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastFertilizeDate");

                    b.Property<DateTimeOffset>("LastRepotDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lastRepotDate");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speciesName");

                    b.HasKey("PlantName", "UserId")
                        .HasName("PKComposite_NameId");

                    b.ToTable("plants");

                    b.HasData(
                        new
                        {
                            PlantName = "ZZ",
                            UserId = 1,
                            DateAcquired = new DateTimeOffset(new DateTime(2022, 5, 7, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(2355), new TimeSpan(0, -7, 0, 0, 0)),
                            LastFertilizeDate = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(2395), new TimeSpan(0, -7, 0, 0, 0)),
                            LastRepotDate = new DateTimeOffset(new DateTime(2022, 5, 14, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(2393), new TimeSpan(0, -7, 0, 0, 0)),
                            SpeciesName = "Zanzibar Gem"
                        },
                        new
                        {
                            PlantName = "Lily",
                            UserId = 1,
                            DateAcquired = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(3454), new TimeSpan(0, -7, 0, 0, 0)),
                            LastFertilizeDate = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(3469), new TimeSpan(0, -7, 0, 0, 0)),
                            LastRepotDate = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(3467), new TimeSpan(0, -7, 0, 0, 0)),
                            SpeciesName = "Peace Lily"
                        },
                        new
                        {
                            PlantName = "Loser",
                            UserId = 2,
                            DateAcquired = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(4457), new TimeSpan(0, -7, 0, 0, 0)),
                            LastFertilizeDate = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(4472), new TimeSpan(0, -7, 0, 0, 0)),
                            LastRepotDate = new DateTimeOffset(new DateTime(2022, 5, 21, 13, 48, 24, 88, DateTimeKind.Unspecified).AddTicks(4470), new TimeSpan(0, -7, 0, 0, 0)),
                            SpeciesName = "Peace Lily"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
